from __future__ import annotations

import json
import re
from dataclasses import dataclass
from pathlib import Path


@dataclass
class Port:
    direction: str
    name: str
    width: int


@dataclass
class Assign:
    lhs: str
    rhs: str


def _strip_comments(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.DOTALL)
    text = re.sub(r"//.*", "", text)
    return text


def _width_from_range(rng: str | None) -> int:
    if not rng:
        return 1
    m = re.match(r"\[(\d+)\s*:\s*(\d+)\]", rng)
    if not m:
        return 1
    msb = int(m.group(1))
    lsb = int(m.group(2))
    return abs(msb - lsb) + 1


def _parse_ports(port_blob: str) -> list[Port]:
    ports: list[Port] = []
    parts = [p.strip() for p in port_blob.replace("\n", " ").split(",") if p.strip()]
    for part in parts:
        m = re.match(
            r"^(input|output|inout)\s+(?:wire\s+|reg\s+)?(\[[^\]]+\])?\s*([A-Za-z_][A-Za-z0-9_]*)$",
            part,
        )
        if not m:
            continue
        ports.append(
            Port(
                direction=m.group(1),
                name=m.group(3),
                width=_width_from_range(m.group(2)),
            )
        )
    return ports


def _parse_assigns(body: str) -> list[Assign]:
    assigns: list[Assign] = []
    for m in re.finditer(r"assign\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?);", body, flags=re.DOTALL):
        lhs = m.group(1).strip()
        rhs = " ".join(m.group(2).split())
        assigns.append(Assign(lhs=lhs, rhs=rhs))
    return assigns


def _emit_gap(gaps: list[dict], kind: str, detail: str, source_file: Path) -> None:
    gaps.append(
        {
            "severity": "medium",
            "kind": kind,
            "reason": detail,
            "source_file": str(source_file),
        }
    )


def _convert_literal(tok: str, gaps: list[dict], source_file: Path) -> str:
    m = re.match(r"^(\d+)'([bdhBDH])([0-9a-fA-F_xXzZ]+)$", tok)
    if not m:
        return tok
    base = m.group(2).lower()
    raw = m.group(3).replace("_", "")
    if "x" in raw.lower() or "z" in raw.lower():
        _emit_gap(gaps, "unsupported-literal", f"x/z literal not supported: {tok}", source_file)
        return "0"
    try:
        if base == "b":
            return str(int(raw, 2))
        if base == "h":
            return str(int(raw, 16))
        return str(int(raw, 10))
    except ValueError:
        _emit_gap(gaps, "unsupported-literal", f"literal parse failed: {tok}", source_file)
        return "0"


def _convert_expr(expr: str, known_signals: set[str], gaps: list[dict], source_file: Path) -> str:
    if "{" in expr or "}" in expr:
        _emit_gap(gaps, "unsupported-expression", f"concatenation unsupported: {expr}", source_file)
        return "0"
    if "?" in expr and ":" in expr:
        _emit_gap(gaps, "unsupported-expression", f"ternary unsupported: {expr}", source_file)
        return "0"

    token_re = re.compile(r"[A-Za-z_][A-Za-z0-9_]*|\d+'[bdhBDH][0-9a-fA-F_xXzZ]+|\d+|==|!=|<=|>=|&&|\|\||<<|>>|[-+*/%&|^~()<>!]")
    converted: list[str] = []
    for tok in token_re.findall(expr):
        if re.match(r"^[A-Za-z_]", tok):
            converted.append(f"self.{tok}" if tok in known_signals else tok)
        elif "'" in tok:
            converted.append(_convert_literal(tok, gaps, source_file))
        else:
            if tok == "&&":
                tok = "&"
            elif tok == "||":
                tok = "|"
            converted.append(tok)
    return " ".join(converted) if converted else "0"


def convert_verilog_to_amaranth(verilog_path: Path, out_dir: Path) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)
    gaps: list[dict] = []

    raw = verilog_path.read_text(encoding="utf-8")
    text = _strip_comments(raw)

    m = re.search(r"module\s+([A-Za-z_][A-Za-z0-9_]*)\s*\((.*?)\)\s*;(.*)endmodule", text, flags=re.DOTALL)
    if not m:
        raise ValueError(f"Could not parse module in {verilog_path}")

    module_name = m.group(1)
    port_blob = m.group(2)
    body = m.group(3)

    ports = _parse_ports(port_blob)
    assigns = _parse_assigns(body)

    if re.search(r"\balways\b", body):
        _emit_gap(gaps, "unsupported-construct", "always blocks unsupported in subset converter", verilog_path)
    if re.search(r"\bgenerate\b", body):
        _emit_gap(gaps, "unsupported-construct", "generate blocks unsupported in subset converter", verilog_path)
    if re.search(r"\bcase\b", body):
        _emit_gap(gaps, "unsupported-construct", "case statements unsupported in subset converter", verilog_path)

    known_signals = {p.name for p in ports}
    internal_lhs = sorted({a.lhs for a in assigns if a.lhs not in known_signals})
    known_signals.update(internal_lhs)

    lines: list[str] = []
    lines.append("# Auto-generated by awto-verilog2amaranth subset converter.")
    lines.append("# Supported: ANSI-style port declarations and continuous assign statements.")
    lines.append("from amaranth import Elaboratable, Module, Signal")
    lines.append("")
    lines.append(f"class {module_name.capitalize()}(Elaboratable):")
    lines.append("    def __init__(self):")

    if not ports and not internal_lhs:
        lines.append("        pass")
    else:
        for p in ports:
            if p.width == 1:
                lines.append(f"        self.{p.name} = Signal()")
            else:
                lines.append(f"        self.{p.name} = Signal({p.width})")
        for name in internal_lhs:
            lines.append(f"        self.{name} = Signal()")

    lines.append("")
    lines.append("    def elaborate(self, platform):")
    lines.append("        m = Module()")
    for a in assigns:
        rhs = _convert_expr(a.rhs, known_signals, gaps, verilog_path)
        lines.append(f"        m.d.comb += self.{a.lhs}.eq({rhs})")
    lines.append("        return m")

    py_out = out_dir / f"{module_name}.py"
    py_out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    gaps_path = out_dir / f"{module_name}.gaps.jsonl"
    with gaps_path.open("w", encoding="utf-8") as f:
        for g in gaps:
            f.write(json.dumps(g, sort_keys=True) + "\n")

    status = {
        "module": module_name,
        "source": str(verilog_path),
        "output": str(py_out),
        "ports": len(ports),
        "assigns": len(assigns),
        "gaps": len(gaps),
        "gaps_file": str(gaps_path),
    }
    (out_dir / f"{module_name}.status.json").write_text(json.dumps(status, indent=2) + "\n", encoding="utf-8")
    return status
